# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adapter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='adapter.proto',
  package='voltha',
  syntax='proto3',
  serialized_pb=_b('\n\radapter.proto\x12\x06voltha\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x0c\x63ommon.proto\"@\n\rAdapterConfig\x12/\n\x11\x61\x64\x64itional_config\x18@ \x01(\x0b\x32\x14.google.protobuf.Any\"r\n\x07\x41\x64\x61pter\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x06\x63onfig\x18\x10 \x01(\x0b\x32\x15.voltha.AdapterConfig\x12\x34\n\x16\x61\x64\x64itional_description\x18@ \x01(\x0b\x32\x14.google.protobuf.Any\"*\n\x08\x41\x64\x61pters\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.voltha.Adapter\")\n\nDeviceType\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x61pter\x18\x02 \x01(\t\"0\n\x0b\x44\x65viceTypes\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.voltha.DeviceType\"\xfe\x01\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04root\x18\x03 \x01(\x08\x12\x11\n\tparent_id\x18\x04 \x01(\t\x12\x0e\n\x06vendor\x18\x05 \x01(\t\x12\r\n\x05model\x18\x06 \x01(\t\x12\x18\n\x10hardware_version\x18\x07 \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x08 \x01(\t\x12\x18\n\x10software_version\x18\t \x01(\t\x12\x15\n\rserial_number\x18\n \x01(\t\x12\x0f\n\x07\x61\x64\x61pter\x18\x0b \x01(\t\x12$\n\x06\x63ustom\x18@ \x01(\x0b\x32\x14.google.protobuf.Any2c\n\x0e\x41\x64\x61pterService\x12Q\n\x0cListAdapters\x12\x16.google.protobuf.Empty\x1a\x10.voltha.Adapters\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/local/adaptersb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADAPTERCONFIG = _descriptor.Descriptor(
  name='AdapterConfig',
  full_name='voltha.AdapterConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='additional_config', full_name='voltha.AdapterConfig.additional_config', index=0,
      number=64, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=189,
)


_ADAPTER = _descriptor.Descriptor(
  name='Adapter',
  full_name='voltha.Adapter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='voltha.Adapter.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config', full_name='voltha.Adapter.config', index=1,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='additional_description', full_name='voltha.Adapter.additional_description', index=2,
      number=64, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=305,
)


_ADAPTERS = _descriptor.Descriptor(
  name='Adapters',
  full_name='voltha.Adapters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='voltha.Adapters.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=349,
)


_DEVICETYPE = _descriptor.Descriptor(
  name='DeviceType',
  full_name='voltha.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='voltha.DeviceType.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adapter', full_name='voltha.DeviceType.adapter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=392,
)


_DEVICETYPES = _descriptor.Descriptor(
  name='DeviceTypes',
  full_name='voltha.DeviceTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='voltha.DeviceTypes.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=442,
)


_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='voltha.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='voltha.Device.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='voltha.Device.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='root', full_name='voltha.Device.root', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='voltha.Device.parent_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vendor', full_name='voltha.Device.vendor', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='voltha.Device.model', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware_version', full_name='voltha.Device.hardware_version', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firmware_version', full_name='voltha.Device.firmware_version', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='software_version', full_name='voltha.Device.software_version', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='voltha.Device.serial_number', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adapter', full_name='voltha.Device.adapter', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom', full_name='voltha.Device.custom', index=11,
      number=64, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=699,
)

_ADAPTERCONFIG.fields_by_name['additional_config'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ADAPTER.fields_by_name['config'].message_type = _ADAPTERCONFIG
_ADAPTER.fields_by_name['additional_description'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ADAPTERS.fields_by_name['items'].message_type = _ADAPTER
_DEVICETYPES.fields_by_name['items'].message_type = _DEVICETYPE
_DEVICE.fields_by_name['custom'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['AdapterConfig'] = _ADAPTERCONFIG
DESCRIPTOR.message_types_by_name['Adapter'] = _ADAPTER
DESCRIPTOR.message_types_by_name['Adapters'] = _ADAPTERS
DESCRIPTOR.message_types_by_name['DeviceType'] = _DEVICETYPE
DESCRIPTOR.message_types_by_name['DeviceTypes'] = _DEVICETYPES
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE

AdapterConfig = _reflection.GeneratedProtocolMessageType('AdapterConfig', (_message.Message,), dict(
  DESCRIPTOR = _ADAPTERCONFIG,
  __module__ = 'adapter_pb2'
  # @@protoc_insertion_point(class_scope:voltha.AdapterConfig)
  ))
_sym_db.RegisterMessage(AdapterConfig)

Adapter = _reflection.GeneratedProtocolMessageType('Adapter', (_message.Message,), dict(
  DESCRIPTOR = _ADAPTER,
  __module__ = 'adapter_pb2'
  # @@protoc_insertion_point(class_scope:voltha.Adapter)
  ))
_sym_db.RegisterMessage(Adapter)

Adapters = _reflection.GeneratedProtocolMessageType('Adapters', (_message.Message,), dict(
  DESCRIPTOR = _ADAPTERS,
  __module__ = 'adapter_pb2'
  # @@protoc_insertion_point(class_scope:voltha.Adapters)
  ))
_sym_db.RegisterMessage(Adapters)

DeviceType = _reflection.GeneratedProtocolMessageType('DeviceType', (_message.Message,), dict(
  DESCRIPTOR = _DEVICETYPE,
  __module__ = 'adapter_pb2'
  # @@protoc_insertion_point(class_scope:voltha.DeviceType)
  ))
_sym_db.RegisterMessage(DeviceType)

DeviceTypes = _reflection.GeneratedProtocolMessageType('DeviceTypes', (_message.Message,), dict(
  DESCRIPTOR = _DEVICETYPES,
  __module__ = 'adapter_pb2'
  # @@protoc_insertion_point(class_scope:voltha.DeviceTypes)
  ))
_sym_db.RegisterMessage(DeviceTypes)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'adapter_pb2'
  # @@protoc_insertion_point(class_scope:voltha.Device)
  ))
_sym_db.RegisterMessage(Device)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class AdapterServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListAdapters = channel.unary_unary(
        '/voltha.AdapterService/ListAdapters',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=Adapters.FromString,
        )


class AdapterServiceServicer(object):

  def ListAdapters(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdapterServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListAdapters': grpc.unary_unary_rpc_method_handler(
          servicer.ListAdapters,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=Adapters.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'voltha.AdapterService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaAdapterServiceServicer(object):
  def ListAdapters(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaAdapterServiceStub(object):
  def ListAdapters(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  ListAdapters.future = None


def beta_create_AdapterService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('voltha.AdapterService', 'ListAdapters'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
  }
  response_serializers = {
    ('voltha.AdapterService', 'ListAdapters'): Adapters.SerializeToString,
  }
  method_implementations = {
    ('voltha.AdapterService', 'ListAdapters'): face_utilities.unary_unary_inline(servicer.ListAdapters),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_AdapterService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('voltha.AdapterService', 'ListAdapters'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
  }
  response_deserializers = {
    ('voltha.AdapterService', 'ListAdapters'): Adapters.FromString,
  }
  cardinalities = {
    'ListAdapters': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'voltha.AdapterService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
