# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example_service.proto',
  package='voltha',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x65xample_service.proto\x12\x06voltha\x1a\x0c\x63ommon.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"q\n\x07\x41\x64\x64ress\x12\n\n\x02id\x18\x07 \x01(\t\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0f\n\x07street2\x18\x02 \x01(\t\x12\x0f\n\x07street3\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0b\n\x03zip\x18\x06 \x01(\r\"/\n\tAddresses\x12\"\n\taddresses\x18\x01 \x03(\x0b\x32\x0f.voltha.Address2\x8b\x03\n\x0e\x45xampleService\x12H\n\rCreateAddress\x12\x0f.voltha.Address\x1a\x0f.voltha.Address\"\x15\x82\xd3\xe4\x93\x02\x0f\"\n/addresses:\x01*\x12\x42\n\nGetAddress\x12\n.voltha.ID\x1a\x0f.voltha.Address\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/addresses/{id}\x12M\n\rUpdateAddress\x12\x0f.voltha.Address\x1a\x0f.voltha.Address\"\x1a\x82\xd3\xe4\x93\x02\x14\x32\x0f/addresses/{id}:\x01*\x12L\n\rDeleteAddress\x12\n.voltha.ID\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/addresses/{id}\x12N\n\rListAddresses\x12\x16.google.protobuf.Empty\x1a\x11.voltha.Addresses\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/addressesb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='voltha.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='voltha.Address.id', index=0,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='street', full_name='voltha.Address.street', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='street2', full_name='voltha.Address.street2', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='street3', full_name='voltha.Address.street3', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='voltha.Address.city', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='voltha.Address.state', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zip', full_name='voltha.Address.zip', index=6,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=219,
)


_ADDRESSES = _descriptor.Descriptor(
  name='Addresses',
  full_name='voltha.Addresses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='voltha.Addresses.addresses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=268,
)

_ADDRESSES.fields_by_name['addresses'].message_type = _ADDRESS
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Addresses'] = _ADDRESSES

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'example_service_pb2'
  # @@protoc_insertion_point(class_scope:voltha.Address)
  ))
_sym_db.RegisterMessage(Address)

Addresses = _reflection.GeneratedProtocolMessageType('Addresses', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSES,
  __module__ = 'example_service_pb2'
  # @@protoc_insertion_point(class_scope:voltha.Addresses)
  ))
_sym_db.RegisterMessage(Addresses)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class ExampleServiceStub(object):
  """(placeholder) This is an example service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateAddress = channel.unary_unary(
        '/voltha.ExampleService/CreateAddress',
        request_serializer=Address.SerializeToString,
        response_deserializer=Address.FromString,
        )
    self.GetAddress = channel.unary_unary(
        '/voltha.ExampleService/GetAddress',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=Address.FromString,
        )
    self.UpdateAddress = channel.unary_unary(
        '/voltha.ExampleService/UpdateAddress',
        request_serializer=Address.SerializeToString,
        response_deserializer=Address.FromString,
        )
    self.DeleteAddress = channel.unary_unary(
        '/voltha.ExampleService/DeleteAddress',
        request_serializer=common__pb2.ID.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ListAddresses = channel.unary_unary(
        '/voltha.ExampleService/ListAddresses',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=Addresses.FromString,
        )


class ExampleServiceServicer(object):
  """(placeholder) This is an example service
  """

  def CreateAddress(self, request, context):
    """Create an address record
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAddress(self, request, context):
    """Return an address by ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAddress(self, request, context):
    """Update an existing address record by ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAddress(self, request, context):
    """Delete an address record by ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAddresses(self, request, context):
    """Return a bit more complex objects
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExampleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAddress,
          request_deserializer=Address.FromString,
          response_serializer=Address.SerializeToString,
      ),
      'GetAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GetAddress,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=Address.SerializeToString,
      ),
      'UpdateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAddress,
          request_deserializer=Address.FromString,
          response_serializer=Address.SerializeToString,
      ),
      'DeleteAddress': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAddress,
          request_deserializer=common__pb2.ID.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ListAddresses': grpc.unary_unary_rpc_method_handler(
          servicer.ListAddresses,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=Addresses.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'voltha.ExampleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaExampleServiceServicer(object):
  """(placeholder) This is an example service
  """
  def CreateAddress(self, request, context):
    """Create an address record
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def GetAddress(self, request, context):
    """Return an address by ID
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def UpdateAddress(self, request, context):
    """Update an existing address record by ID
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def DeleteAddress(self, request, context):
    """Delete an address record by ID
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def ListAddresses(self, request, context):
    """Return a bit more complex objects
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaExampleServiceStub(object):
  """(placeholder) This is an example service
  """
  def CreateAddress(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Create an address record
    """
    raise NotImplementedError()
  CreateAddress.future = None
  def GetAddress(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Return an address by ID
    """
    raise NotImplementedError()
  GetAddress.future = None
  def UpdateAddress(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Update an existing address record by ID
    """
    raise NotImplementedError()
  UpdateAddress.future = None
  def DeleteAddress(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Delete an address record by ID
    """
    raise NotImplementedError()
  DeleteAddress.future = None
  def ListAddresses(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Return a bit more complex objects
    """
    raise NotImplementedError()
  ListAddresses.future = None


def beta_create_ExampleService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('voltha.ExampleService', 'CreateAddress'): Address.FromString,
    ('voltha.ExampleService', 'DeleteAddress'): common__pb2.ID.FromString,
    ('voltha.ExampleService', 'GetAddress'): common__pb2.ID.FromString,
    ('voltha.ExampleService', 'ListAddresses'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
    ('voltha.ExampleService', 'UpdateAddress'): Address.FromString,
  }
  response_serializers = {
    ('voltha.ExampleService', 'CreateAddress'): Address.SerializeToString,
    ('voltha.ExampleService', 'DeleteAddress'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
    ('voltha.ExampleService', 'GetAddress'): Address.SerializeToString,
    ('voltha.ExampleService', 'ListAddresses'): Addresses.SerializeToString,
    ('voltha.ExampleService', 'UpdateAddress'): Address.SerializeToString,
  }
  method_implementations = {
    ('voltha.ExampleService', 'CreateAddress'): face_utilities.unary_unary_inline(servicer.CreateAddress),
    ('voltha.ExampleService', 'DeleteAddress'): face_utilities.unary_unary_inline(servicer.DeleteAddress),
    ('voltha.ExampleService', 'GetAddress'): face_utilities.unary_unary_inline(servicer.GetAddress),
    ('voltha.ExampleService', 'ListAddresses'): face_utilities.unary_unary_inline(servicer.ListAddresses),
    ('voltha.ExampleService', 'UpdateAddress'): face_utilities.unary_unary_inline(servicer.UpdateAddress),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_ExampleService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('voltha.ExampleService', 'CreateAddress'): Address.SerializeToString,
    ('voltha.ExampleService', 'DeleteAddress'): common__pb2.ID.SerializeToString,
    ('voltha.ExampleService', 'GetAddress'): common__pb2.ID.SerializeToString,
    ('voltha.ExampleService', 'ListAddresses'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
    ('voltha.ExampleService', 'UpdateAddress'): Address.SerializeToString,
  }
  response_deserializers = {
    ('voltha.ExampleService', 'CreateAddress'): Address.FromString,
    ('voltha.ExampleService', 'DeleteAddress'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
    ('voltha.ExampleService', 'GetAddress'): Address.FromString,
    ('voltha.ExampleService', 'ListAddresses'): Addresses.FromString,
    ('voltha.ExampleService', 'UpdateAddress'): Address.FromString,
  }
  cardinalities = {
    'CreateAddress': cardinality.Cardinality.UNARY_UNARY,
    'DeleteAddress': cardinality.Cardinality.UNARY_UNARY,
    'GetAddress': cardinality.Cardinality.UNARY_UNARY,
    'ListAddresses': cardinality.Cardinality.UNARY_UNARY,
    'UpdateAddress': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'voltha.ExampleService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
