FROM lyft/envoy:latest

RUN apt-get update && apt-get -q install -y \
    curl
ADD envoy/front-proxy /envoy/
ADD pki /envoy/
ADD envoy/go/envoyd/envoyd /usr/local/bin

CMD /usr/local/bin/envoy -c /envoy/front-proxy/voltha-grpc-proxy.json
