FROM lyft/envoy:29361deae91575a1d46c7a21e913f19e75622ebe

RUN apt-get update && apt-get -q install -y \
    curl
COPY envoy/front-proxy /envoy/
COPY envoy/proto.pb /envoy/
COPY pki /envoy/
COPY envoy/go/envoyd/envoyd /usr/local/bin

CMD /usr/local/bin/envoy -c /envoy/front-proxy/voltha-grpc-proxy.json
