FROM lyft/envoy:092f01381467dfc3324e5e9528c67ee5d65744fd

RUN apt-get update && apt-get -q install -y \
    curl
ADD envoy/front-proxy /envoy/
ADD envoy/proto.pb /envoy/
ADD pki /envoy/
ADD envoy/go/envoyd/envoyd /usr/local/bin

CMD /usr/local/bin/envoy -c /envoy/front-proxy/voltha-grpc-proxy.json
