# Copyright 2017-present Adtran, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


olt_state_json = {
    "software-version": "ngpon2_agent-13.0.32-1.657.815547",
    "pon": [{
        "pon-id": 0,
        "downstream-channel-id": 15,
        "onu": [{
            "onu-id": 0,
            "reported-password": "redacted",
            "rssi": -207,
            "equalization-delay": 620952,
            "fiber-length": 47,
            "op-code": 0,
            "response-code": 0
        }],
        "ont-los": [],
        "gem": [{
            "port-id": 2176,
            "tx-packets": 65405,
            "rx-packets": 13859,
            "tx-bytes": "5420931",
            "rx-bytes": "3242784",
            "of-port-name": "pon0_128",
            "onu-id": 0,
            "alloc-id": 1024
        }, {
            "port-id": 2308,
            "tx-packets": 763461880,
            "rx-packets": 1619060062,
            "tx-bytes": "141303946790728",
            "rx-bytes": "145149180973448",
            "of-port-name": "pon0_4",
            "onu-id": 0,
            "alloc-id": 1024
        }, {
            "port-id": 2309,
            "tx-packets": 18,
            "rx-packets": 9272150,
            "tx-bytes": "1152",
            "rx-bytes": "593417600",
            "of-port-name": "pon0_5",
            "onu-id": 0,
            "alloc-id": 1024
        }],
        "rx-packets": 1625773517,
        "rx-bytes": "145149613233620",
        "tx-packets": 761098346,
        "tx-bytes": "141303797318481",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "gAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 1,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 2,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 3,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 4,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 5,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 6,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 7,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 8,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 9,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 10,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 11,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 12,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 13,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 14,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }, {
        "pon-id": 15,
        "downstream-channel-id": 255,
        "ont-los": [],
        "rx-packets": 0,
        "rx-bytes": "0",
        "tx-packets": 0,
        "tx-bytes": "0",
        "tx-bip-errors": 0,
        "wm-tuned-out-onus": "AAAAAAAAAAAAAAAAAAAAAA==",
        "ra-complete-onus": "AAAAAAAAAAAAAAAAAAAAAA=="
    }]
}
