version: "3.2"
services:

#
# Deploying a Fluentd cluster using this file assumes that overlay network 'voltha_net'
# has already been created. To deploy the fluentd cluster, issue the command:
#
#     docker stack deploy -c docker-compose-fluentd-cluster.yml fluentd
#
# This spins up two Fluentd Forwarders and one each Fluentd Aggregator-Active, Fluentd Aggregator-Standby.
# The forwards listens for voltha components logs on port 23224 and sends them towards Fluentd Aggregator. 
# Fluentd Aggregator writes them to their host mounted disk
#

  fluentdactv:
    image: "${REGISTRY}voltha/fluentd:${TAG:-latest}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
        FLUENTD_CONF: fluent-agg.conf
    networks:
      - voltha-net
    ports:
      - "24224"
    volumes:
      - ${VOLTHA_LOGS:-/var/log/voltha/logging_volume}:/fluentd/log

  fluentdstby:
    image: "${REGISTRY}voltha/fluentd:${TAG:-latest}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
        FLUENTD_CONF: fluent-agg.conf
    networks:
      - voltha-net
    ports:
      - "24224"
    volumes:
      - ${VOLTHA_LOGS:-/var/log/voltha/logging_volume}:/fluentd/log

networks:
  voltha-net:
    external:
      name: voltha_net

