#
# This stackfile deploys grafana to a docker swarm.
#
# Grafana  depends on:
# - voltha_net (overlay network)
#
# To deploy the stack, issue the command:
#
#     docker stack deploy -c docker-compose-grafana-swarm.yml grafana
#

version: "3"
services:
  grafana:
    image: kamon/grafana_graphite
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    deploy:
      replicas: 1
    environment:
      GR_SERVER_ROOT_URL: "http://localhost:80/grafana/"
    networks:
      - voltha-net
    ports:
    - "8883:80"
    - "2003:2003"
    - "2004:2004"
    - "8126:8126"
    - "8125:8125/udp"

networks:
  voltha-net:
    external:
      name: voltha_net

