# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder "../", "/voltha", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder "../", "/voltha"
  end

  config.vm.define "voltha" do |d|
    d.vm.box = "rrashidi/voltha-base"
    d.vm.hostname = "voltha"
    d.vm.network "private_network", ip: "10.100.198.220"
    d.vm.provision :shell, inline: "cd /voltha && source env.sh && chmod 777 /tmp/fluentd"
  end

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

end
